apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: hello
    tier: frontend
    track: stable
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 80
    targetPort: 80
  