apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: hello
    tier: backend
    track: stable
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000