name: Docker CI/CD for server

on:
  push:
    branches: ["main", "tam-k8s-docker-CI-CD" ]
  pull_request:
    branches: [ "main" ]



jobs:

  build-docker:

    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v3
    - name: Build the backend Docker image
      run: |
        docker build -t backend-golang --target program .
        docker build -t mysql-db --target db .
      working-directory: ./backend
    
    - name: Build the frontend Docker image
      run: |
        docker build -t frontend .
      working-directory: ./frontend

    - name: Show images 
      run: docker images
    
    - name: Run docker compose to test
      run : |
        docker-compose up -d
    
    - name: Show container
      run: docker ps

    - name: Stop docker compose
      run : |
        docker compose stop

  run-test:
    needs: build-docker
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v3
    - name: Build the backend Docker image
      run: |
        docker build -t backend-golang --target program .
        docker build -t mysql-db --target db .
      working-directory: ./backend
    
    - name: Build the frontend Docker image
      run: |
        docker build -t frontend .
      working-directory: ./frontend

    - name: Run docker compose to test
      run : |
        docker-compose up -d


    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install library 
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run fake data
      run: |
        python3 fake.py
      working-directory: ./fake-data

    - name: run test case
      run : |
        python3 -m unittest tests.test_user
        python3 -m unittest tests.test_category
        python3 -m unittest tests.test_product
        python3 -m unittest tests.test_cart
      working-directory: ./test_case


    - name: Stop docker compose
      run : |
        docker compose stop
  